# frozen_string_literal: true

# Dungeon Master's Guide, 5th Edition, page 134
Gemstone.create!(name: 'Azurite', description: 'opaque mottled deep blue', cost_in_gp: 10)
Gemstone.create!(name: 'Banded agate', description: 'translucent striped brown, blue, white, or red', cost_in_gp: 10)
Gemstone.create!(name: 'Blue quartz', description: 'transparent pale blue', cost_in_gp: 10)
Gemstone.create!(name: 'Eye agate', description: 'translucent circles of gray, white, brown, blue , or green', cost_in_gp: 10)
Gemstone.create!(name: 'Hematite', description: 'opaque gray-black', cost_in_gp: 10)
Gemstone.create!(name: 'Lapis lazuli', description: 'opaque light and dark blue with yellow flecks', cost_in_gp: 10)
Gemstone.create!(name: 'Malachite', description: 'opaque striated light and dark green', cost_in_gp: 10)
Gemstone.create!(name: 'Moss agate', description: 'translucent pink or yellow-white with mossy gray or green markings', cost_in_gp: 10)
Gemstone.create!(name: 'Obsidian', description: 'opaque black', cost_in_gp: 10)
Gemstone.create!(name: 'Rhodochrosite', description: 'opaque light pink', cost_in_gp: 10)
Gemstone.create!(name: 'Tiger eye', description: 'translucent brown with golden center', cost_in_gp: 10)
Gemstone.create!(name: 'Turquoise', description: 'opaque light blue-green', cost_in_gp: 10)
Gemstone.create!(name: 'Bloodstone', description: 'opaque dark gray with red flecks', cost_in_gp: 50)
Gemstone.create!(name: 'Carnelian', description: 'opaque orange to red-brown', cost_in_gp: 50)
Gemstone.create!(name: 'Chalcedony', description: 'opaque white', cost_in_gp: 50)
Gemstone.create!(name: 'Chrysoprase', description: 'translucent green', cost_in_gp: 50)
Gemstone.create!(name: 'Citrine', description: 'transparent pale yellow-brown', cost_in_gp: 50)
Gemstone.create!(name: 'Jasper', description: 'opaque blue, black, or brown', cost_in_gp: 50)
Gemstone.create!(name: 'Moonstone', description: 'translucent white with pale blue glow', cost_in_gp: 50)
Gemstone.create!(name: 'Onyx', description: 'opaque bands of black and white, or pure black or white)', cost_in_gp: 50)
Gemstone.create!(name: 'Quartz', description: 'transparent white, smoky gray, or yellow', cost_in_gp: 50)
Gemstone.create!(name: 'Sardonyx', description: 'opaque bands of red and white', cost_in_gp: 50)
Gemstone.create!(name: 'Star rose quartz', description: 'translucent rosy stone with white star-shaped center', cost_in_gp: 50)
Gemstone.create!(name: 'Zircon', description: 'transparent pale blue-green', cost_in_gp: 50)
Gemstone.create!(name: 'Amber', description: 'transparent watery gold to rich gold', cost_in_gp: 100)
Gemstone.create!(name: 'Amethyst', description: 'transparent deep purple', cost_in_gp: 100)
Gemstone.create!(name: 'Chrysoberyl', description: 'transparent yellow-green to pale green', cost_in_gp: 100)
Gemstone.create!(name: 'Coral', description: 'opaque crimson', cost_in_gp: 100)
Gemstone.create!(name: 'Garnet', description: 'transparent red, brown-green , or violet', cost_in_gp: 100)
Gemstone.create!(name: 'Jade', description: 'translucent light green, deep green , or white', cost_in_gp: 100)
Gemstone.create!(name: 'Jet', description: 'opaque deep black', cost_in_gp: 100)
Gemstone.create!(name: 'Pearl', description: 'opaque lustrous white , yellow, or pink', cost_in_gp: 100)
Gemstone.create!(name: 'Spinel', description: 'transparent red, red-brown, or deep green', cost_in_gp: 100)
Gemstone.create!(name: 'Tourmaline', description: 'transparent pale green , blue, brown , or red', cost_in_gp: 100)
Gemstone.create!(name: 'Alexandrite', description: 'transparent dark green', cost_in_gp: 500)
Gemstone.create!(name: 'Aquamarine', description: 'transparent pale blue-green', cost_in_gp: 500)
Gemstone.create!(name: 'Black pearl', description: 'opaque pure black', cost_in_gp: 500)
Gemstone.create!(name: 'Blue spinel', description: 'transparent deep blue', cost_in_gp: 500)
Gemstone.create!(name: 'Peridot', description: 'transparent rich olive green', cost_in_gp: 500)
Gemstone.create!(name: 'Topaz', description: 'transparent golden yellow', cost_in_gp: 500)
Gemstone.create!(name: 'Black opal', description: 'translucent dark green with black mottling and golden flecks', cost_in_gp: 1_000)
Gemstone.create!(name: 'Blue sapphire', description: 'transparent blue-white to medium blue', cost_in_gp: 1_000)
Gemstone.create!(name: 'Emerald', description: 'transparent deep bright green', cost_in_gp: 1_000)
Gemstone.create!(name: 'Fire opal', description: 'translucent fiery red', cost_in_gp: 1_000)
Gemstone.create!(name: 'Opal', description: 'translucent pale blue with green and golden mottling', cost_in_gp: 1_000)
Gemstone.create!(name: 'Star ruby', description: 'translucent ruby with white star-shaped center', cost_in_gp: 1_000)
Gemstone.create!(name: 'Star sapphire', description: 'translucent blue sapphire with white star-shaped center', cost_in_gp: 1_000)
Gemstone.create!(name: 'Yellow sapphire', description: 'transparent fiery yellow or yellow-green', cost_in_gp: 1_000)
Gemstone.create!(name: 'Black sapphire', description: 'translucent lustrous black with glowing highlights', cost_in_gp: 5_000)
Gemstone.create!(name: 'Diamond', description: 'transparent blue-white, canary, pink, brown, or blue', cost_in_gp: 5_000)
Gemstone.create!(name: 'Jacinth', description: 'transparent fiery orange)', cost_in_gp: 5_000)
Gemstone.create!(name: 'Ruby', description: 'transparent clear red to deep crimson', cost_in_gp: 5_000)

# Dungeon Master's Guide, 5th Edition, page 134
ArtObject.create!(name: 'Silver ewer', cost_in_gp: 25)
ArtObject.create!(name: 'Carved bone statuette', cost_in_gp: 25)
ArtObject.create!(name: 'Small gold bracelet', cost_in_gp: 25)
ArtObject.create!(name: 'Cloth-of-gold vestments', cost_in_gp: 25)
ArtObject.create!(name: 'Black velvet mask stitched with silver thread', cost_in_gp: 25)
ArtObject.create!(name: 'Copper chalice with silver filigree', cost_in_gp: 25)
ArtObject.create!(name: 'Pair of engraved bone dice', cost_in_gp: 25)
ArtObject.create!(name: 'Small mirror set in a painted wooden frame', cost_in_gp: 25)
ArtObject.create!(name: 'Embroidered silk handkerchief', cost_in_gp: 25)
ArtObject.create!(name: 'Gold locket with a painted portrait inside', cost_in_gp: 25)
ArtObject.create!(name: 'Gold ring set with bloodstones', cost_in_gp: 250)
ArtObject.create!(name: 'Carved ivory statuette', cost_in_gp: 250)
ArtObject.create!(name: 'Large gold bracelet', cost_in_gp: 250)
ArtObject.create!(name: 'Silver necklace with a gemstone pendant', cost_in_gp: 250)
ArtObject.create!(name: 'Bronze crown', cost_in_gp: 250)
ArtObject.create!(name: 'Silk robe with gold embroidery', cost_in_gp: 250)
ArtObject.create!(name: 'Large well-made tapestry', cost_in_gp: 250)
ArtObject.create!(name: 'Brass mug with jade inlay', cost_in_gp: 250)
ArtObject.create!(name: 'Box of turquoise animal figurines', cost_in_gp: 250)
ArtObject.create!(name: 'Gold bird cage with electrum filigree', cost_in_gp: 250)
ArtObject.create!(name: 'Silver chalice set with moonstones', cost_in_gp: 750)
ArtObject.create!(name: 'Silver-plated steel longsword with jet set in hilt', cost_in_gp: 750)
ArtObject.create!(name: 'Carved harp of exotic wood with ivory inlay and zircon gems', cost_in_gp: 750)
ArtObject.create!(name: 'Small gold idol', cost_in_gp: 750)
ArtObject.create!(name: 'Gold dragon comb set with red garnets as eyes', cost_in_gp: 750)
ArtObject.create!(name: 'Bottle stopper cork embossed with gold leaf and set with amethysts', cost_in_gp: 750)
ArtObject.create!(name: 'Ceremonial electrum dagger with a black pearl in the pommel', cost_in_gp: 750)
ArtObject.create!(name: 'Silver and gold brooch', cost_in_gp: 750)
ArtObject.create!(name: 'Obsidian statuette with gold fittings and inlay', cost_in_gp: 750)
ArtObject.create!(name: 'Painted gold war mask', cost_in_gp: 750)
ArtObject.create!(name: 'Fine gold chain set with a fire opal', cost_in_gp: 2500)
ArtObject.create!(name: 'Old masterpiece painting', cost_in_gp: 2500)
ArtObject.create!(name: 'Embroidered silk and velvet mantle set with numerous moonstones', cost_in_gp: 2500)
ArtObject.create!(name: 'Platinum bracelet set with a sapphire', cost_in_gp: 2500)
ArtObject.create!(name: 'Embroidered glove set with jewel chips', cost_in_gp: 2500)
ArtObject.create!(name: 'jeweled anklet', cost_in_gp: 2500)
ArtObject.create!(name: 'Gold music box', cost_in_gp: 2500)
ArtObject.create!(name: 'Gold circlet set with four aquamarines', cost_in_gp: 2500)
ArtObject.create!(name: 'Eye patch with a mock eye set in blue sapphire and moonstone', cost_in_gp: 2500)
ArtObject.create!(name: 'A necklace string of small pink pearls', cost_in_gp: 2500)
ArtObject.create!(name: 'Jeweled gold crown', cost_in_gp: 7500)
ArtObject.create!(name: 'jeweled platinum ring', cost_in_gp: 7500)
ArtObject.create!(name: 'Small gold statuette set with rubies', cost_in_gp: 7500)
ArtObject.create!(name: 'Gold cup set with emeralds', cost_in_gp: 7500)
ArtObject.create!(name: 'Gold jewelry box with platinum filigree', cost_in_gp: 7500)
ArtObject.create!(name: 'Painted gold child\'s sarcophagus', cost_in_gp: 7500)
ArtObject.create!(name: 'jade game board with solid gold playing pieces', cost_in_gp: 7500)
ArtObject.create!(name: 'Bejeweled ivory drinking horn with gold filigree', cost_in_gp: 7500)
