# frozen_string_literal: true

# Dungeon Master's Guide, 5th Edition, page 134
Gemstone.create!(name: 'Azurite', description: 'opaque mottled deep blue', cost_in_gp: 10)
Gemstone.create!(name: 'Banded agate', description: 'translucent striped brown, blue, white, or red', cost_in_gp: 10)
Gemstone.create!(name: 'Blue quartz', description: 'transparent pale blue', cost_in_gp: 10)
Gemstone.create!(name: 'Eye agate', description: 'translucent circles of gray, white, brown, blue , or green', cost_in_gp: 10)
Gemstone.create!(name: 'Hematite', description: 'opaque gray-black', cost_in_gp: 10)
Gemstone.create!(name: 'Lapis lazuli', description: 'opaque light and dark blue with yellow flecks', cost_in_gp: 10)
Gemstone.create!(name: 'Malachite', description: 'opaque striated light and dark green', cost_in_gp: 10)
Gemstone.create!(name: 'Moss agate', description: 'translucent pink or yellow-white with mossy gray or green markings', cost_in_gp: 10)
Gemstone.create!(name: 'Obsidian', description: 'opaque black', cost_in_gp: 10)
Gemstone.create!(name: 'Rhodochrosite', description: 'opaque light pink', cost_in_gp: 10)
Gemstone.create!(name: 'Tiger eye', description: 'translucent brown with golden center', cost_in_gp: 10)
Gemstone.create!(name: 'Turquoise', description: 'opaque light blue-green', cost_in_gp: 10)
Gemstone.create!(name: 'Bloodstone', description: 'opaque dark gray with red flecks', cost_in_gp: 50)
Gemstone.create!(name: 'Carnelian', description: 'opaque orange to red-brown', cost_in_gp: 50)
Gemstone.create!(name: 'Chalcedony', description: 'opaque white', cost_in_gp: 50)
Gemstone.create!(name: 'Chrysoprase', description: 'translucent green', cost_in_gp: 50)
Gemstone.create!(name: 'Citrine', description: 'transparent pale yellow-brown', cost_in_gp: 50)
Gemstone.create!(name: 'Jasper', description: 'opaque blue, black, or brown', cost_in_gp: 50)
Gemstone.create!(name: 'Moonstone', description: 'translucent white with pale blue glow', cost_in_gp: 50)
Gemstone.create!(name: 'Onyx', description: 'opaque bands of black and white, or pure black or white)', cost_in_gp: 50)
Gemstone.create!(name: 'Quartz', description: 'transparent white, smoky gray, or yellow', cost_in_gp: 50)
Gemstone.create!(name: 'Sardonyx', description: 'opaque bands of red and white', cost_in_gp: 50)
Gemstone.create!(name: 'Star rose quartz', description: 'translucent rosy stone with white star-shaped center', cost_in_gp: 50)
Gemstone.create!(name: 'Zircon', description: 'transparent pale blue-green', cost_in_gp: 50)
Gemstone.create!(name: 'Amber', description: 'transparent watery gold to rich gold', cost_in_gp: 100)
Gemstone.create!(name: 'Amethyst', description: 'transparent deep purple', cost_in_gp: 100)
Gemstone.create!(name: 'Chrysoberyl', description: 'transparent yellow-green to pale green', cost_in_gp: 100)
Gemstone.create!(name: 'Coral', description: 'opaque crimson', cost_in_gp: 100)
Gemstone.create!(name: 'Garnet', description: 'transparent red, brown-green , or violet', cost_in_gp: 100)
Gemstone.create!(name: 'Jade', description: 'translucent light green, deep green , or white', cost_in_gp: 100)
Gemstone.create!(name: 'Jet', description: 'opaque deep black', cost_in_gp: 100)
Gemstone.create!(name: 'Pearl', description: 'opaque lustrous white , yellow, or pink', cost_in_gp: 100)
Gemstone.create!(name: 'Spinel', description: 'transparent red, red-brown, or deep green', cost_in_gp: 100)
Gemstone.create!(name: 'Tourmaline', description: 'transparent pale green , blue, brown , or red', cost_in_gp: 100)
Gemstone.create!(name: 'Alexandrite', description: 'transparent dark green', cost_in_gp: 500)
Gemstone.create!(name: 'Aquamarine', description: 'transparent pale blue-green', cost_in_gp: 500)
Gemstone.create!(name: 'Black pearl', description: 'opaque pure black', cost_in_gp: 500)
Gemstone.create!(name: 'Blue spinel', description: 'transparent deep blue', cost_in_gp: 500)
Gemstone.create!(name: 'Peridot', description: 'transparent rich olive green', cost_in_gp: 500)
Gemstone.create!(name: 'Topaz', description: 'transparent golden yellow', cost_in_gp: 500)
Gemstone.create!(name: 'Black opal', description: 'translucent dark green with black mottling and golden flecks', cost_in_gp: 1_000)
Gemstone.create!(name: 'Blue sapphire', description: 'transparent blue-white to medium blue', cost_in_gp: 1_000)
Gemstone.create!(name: 'Emerald', description: 'transparent deep bright green', cost_in_gp: 1_000)
Gemstone.create!(name: 'Fire opal', description: 'translucent fiery red', cost_in_gp: 1_000)
Gemstone.create!(name: 'Opal', description: 'translucent pale blue with green and golden mottling', cost_in_gp: 1_000)
Gemstone.create!(name: 'Star ruby', description: 'translucent ruby with white star-shaped center', cost_in_gp: 1_000)
Gemstone.create!(name: 'Star sapphire', description: 'translucent blue sapphire with white star-shaped center', cost_in_gp: 1_000)
Gemstone.create!(name: 'Yellow sapphire', description: 'transparent fiery yellow or yellow-green', cost_in_gp: 1_000)
Gemstone.create!(name: 'Black sapphire', description: 'translucent lustrous black with glowing highlights', cost_in_gp: 5_000)
Gemstone.create!(name: 'Diamond', description: 'transparent blue-white, canary, pink, brown, or blue', cost_in_gp: 5_000)
Gemstone.create!(name: 'Jacinth', description: 'transparent fiery orange)', cost_in_gp: 5_000)
Gemstone.create!(name: 'Ruby', description: 'transparent clear red to deep crimson', cost_in_gp: 5_000)
